[[redirects]]
  from = "/analytics/nft/:contractAddress/:tokenId"
  to = "/dashboard/nft/[contractAddress]/[tokenId].html?assetId=:contractAddress/:tokenId"
  status = 200

[[redirects]]
  from = "/analytics/collection/:id"
  to = "/dashboard/collection/[id].html?id=:id"
  status = 200

[[redirects]]
  from = "/analytics/user/:address"
  to = "/dashboard/user/[address].html?address=:address"
  status = 200

[[redirects]]
  from = "/analytics"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/analytics/search"
  to = "/dashboard/search.html"
  status = 200