name: Deployment workflow

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v1

      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Staging deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: "out"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NEXT_PUBLIC_GRAPHQL_ENDPOINT: "checking"

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v1

      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: "out"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}